[tool.poetry]
name = "wsidicomizer"
version = "0.1.0"
description = ""
authors = ["Erik O Gabrielsson <erik.o.gabrielsson@sectra.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
wsidicom = {path = "../wsidicom", develop = true}
opentile = {path = "../opentile", develop = true}
imagecodecs = "^2021.8.26"
openslide-python = "^1.1.2"
PyTurboJPEG = "^1.6.1"
numpy = "^1.21.2"
pydicom = "^2.2.1"
highdicom = "^0.9.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cli = "wsidicomizer.cli:main"
